language: java

jdk:
  - oraclejdk8
  
addons:
 sonarcloud:
  organization: "3pillar-labs-github"
  token:
   secure: "yuCJcG9aVn3JdCDmgQq5pEA5WtFuIwyQUlF/mXldK0GcvxPE0YG4EF831FGTd3/SmQm7ee1j15TiGZDenDATJz848itq2d3uDpbm8o39nXQSFvjRnBjnn/S5kJVxpwLQMaIbPbnm8cdfk1aZeXGrudbPDzEkJlL/KRXRibxXgIfIbEpuAFRySfWL7yXXkMk2QuEHNrq+5JtFBlKB5LPCoSI3Ogps4V0/f5SPMfFV/kUSgD1WcBVaVkc3FECprxRtrpK2uWOEwtL+142pWD1ZFiQ9WTeQeLyiOIhQ3bc1Y19AIOOv6A+5bojzrbf/7GSuH3Bi2yQX0jtaRw8XEKhxmAbIRBoNjgiofgYpCHhiDDgqqk0Xi0EwNeaRL2inrEwP4kyKm9xPlsxfyuxyEyG2rszkrw/lf0kOJIn0DXMmTJl7DluQFHsTdR1tJRLRRkUvVixjms6VICAoTPMeV08RBL0wziIgqR1YQAAiTBo5VmaSaOxyzFDB/edGL7/Wj2eBmFDrHdW8G+zK0t34xbAHETYotmUAWEvMdRqDebZP+t/cRBXxMnXGtslRb/wR1IPqqhb5e4/5hsHvWx7gHWobAtSE1h3Q2AgK7SUKRir+0kDDzih1/iOe2HimdUFDMql5E3ejQCK37Qt8xWy3eAC2heCQG5MWDw2HA1QoRao2IUk="

script:
  - sonar-scanner

